name: Generate Changelog

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          github_changelog_generator \
            --user=kodurisandeep \
            --project=etl-pipeline-india-nocloud \
            --token=${{ secrets.PAT_TOKEN }}

      - name: Commit updated CHANGELOG
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
          git push
