name: ETL Pipeline Check

on:
  push:
    branches: [ "dev", "sit", "main" ]
  pull_request:
    branches: [ "dev", "sit", "main" ]

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL pipeline
        env:
          PYTHONPATH: .
        run: |
          python scripts/run_etl.py