name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest=$(git tag --sort=-creatordate | head -n 1)
          echo "latest_tag=${latest:-v0.0.0}" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        run: |
          latest=${{ steps.get_tag.outputs.latest_tag }}
          version=${latest#v}
          IFS='.' read -r major minor patch <<< "$version"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=${new_tag}" >> $GITHUB_OUTPUT

      - name: Create Git tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.bump_version.outputs.new_tag }}
          git push origin ${{ steps.bump_version.outputs.new_tag }}
          gh release create ${{ steps.bump_version.outputs.new_tag }} \
            --title "Release ${{ steps.bump_version.outputs.new_tag }}" \
            --notes "Automated release triggered from main branch."